### ISSUE TITLE
db file not working as downloaded/cloned

### ISSUE THREAD

**Issue by SNOlson** [ppdebreuck/modnet#1]
![image](https://user-images.githubusercontent.com/46797907/84545995-2d763100-acb5-11ea-9fb7-b98ce4cf6ec1.png)

The database file included in the repository is a .pkl.zip file that the featurize() function cannot open whereas in the examples it is just a .pkl file. I tried removing .zip, and attempted to unpickle and pickle the file into the same filename as the examples but have not had any success as I am not understanding pickle very well yet. It is also not unzippable by my 7zip. Is it meant to be the .pkl.zip filetype?

**Comment by ppdebreuck** [comment]
Thanks for reporting this.

You could download it by cloning (but git LFS needs to be installed as this is seen as a large file).
To make it more convenient I have added a figshare link to the database: 
[link](https://figshare.com/articles/feature_database_for_MODNet/12480620). Unzip it, and use the .pkl file.

A fix has been pushed by adding the link in the README.

**Comment by SNOlson** [comment]
Unzipping it works now, thanks!
