### ISSUE TITLE
Presence of discontinuous features

### ISSUE THREAD

**Issue by ml-evs** [ppdebreuck/modnet#137]
As reported by @gbrunin, some of the matminer features can lead to discontinuities in model predictions when scanning through composition space. 

Specifically those that take e.g., `max(atomic number)` and `min(atomic number)` will mess up predictions when going from e.g., FeC to Fe100C100Si1 (random example). We could consider curating a new preset (perhaps following @gbrunin's existing experiments) that removes such featurizers by default.

**Comment by ppdebreuck** [comment]
Has now been merged in the main branch. Featurizers now include a `continuous_only` parameter. See for instance https://github.com/ppdebreuck/modnet/blob/a3432ec00589a281299e3b9e1fc64ccc04189e69/modnet/featurizers/presets/matminer_2023.py#L18
