### ISSUE TITLE
FitGenetic stuck around the end of iterations

### ISSUE THREAD

**Issue by gbrunin** [ppdebreuck/modnet#156]
When using FitGenetic, I sometimes have the following issue: the process stops around the end of an iteration, without throwing an error, and without stopping to run. It's not reproducible, but happens quite often in my case. I run the code on my laptop, in a `main()` method. When it happens, I simply re-run the code and it works (or not, depends on the phase of the moon). Pierre-Paul suspects a problem with parallelization, more precisely a child process that never returns its result. Any clue @ml-evs ?

**Comment by ml-evs** [comment]
Hopefully closed by setting lots of `TF_*` env vars so that TF does not hog all of a CPU at once

**Comment by gbrunin** [comment]
Yep, seems to work. Thanks! 
For anyone having a similar issue, try setting the environment variables:
`export OPENBLAS_NUM_THREADS=1`
`export MKL_NUM_THREADS=1`
`export OMP_NUM_THREADS=1`
`export TF_NUM_INTRAOP_THREADS=1`
`export TF_NUM_INTEROP_THREADS=1`
`export CUDA_VISIBLE_DEVICES=1`

**Comment by ml-evs** [comment]
> `export CUDA_VISIBLE_DEVICES=1`

I think this should be `-1`? Probably this is equivalent unless you have more than 1 GPU on your system...

**Comment by ppdebreuck** [comment]
Yes ! No need of a cuda device
