### ISSUE TITLE
Better pinning of requirements

### ISSUE THREAD

**Issue by ml-evs** [ppdebreuck/modnet#71]
We should make more of an effort to make sure the versions of packages we specify are compatible for each release (using e.g. a maximum version number). Currently, installing v0.1.11 leads to incompatibility between tensorflow and tensorflow-probability versions.

**Comment by ml-evs** [comment]
One suggestion is to provide a requirements.txt with specific pinned versions and also a setup.py that is slightly more free.

**Comment by ppdebreuck** [comment]
I totally agree but this is hard if not impossible, some dependencies are pinning versions that are conflicting with others (matminer <-> TensorFlow).

**Comment by ml-evs** [comment]
It's certainly tedious - if there are conflicts then we should at least make a note of them. I will take a look at this when I get some time.
