### ISSUE TITLE
pip install on Google Colab only working up to version 0.1.6

### ISSUE THREAD

**Issue by sgbaird** [ppdebreuck/modnet#72]
[Google Colab notebook](https://colab.research.google.com/drive/1hw0VKSCWd9JctxUx-TGdF-coNvmq6RIN?usp=sharing)
```python
!pip install --upgrade pip
!pip install modnet==0.1.11
```

> ```python
> Requirement already satisfied: pip in /usr/local/lib/python3.7/dist-packages (21.1.3)
> Collecting pip
>   Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
>      |████████████████████████████████| 1.7 MB 5.2 MB/s 
> Installing collected packages: pip
>   Attempting uninstall: pip
>     Found existing installation: pip 21.1.3
>     Uninstalling pip-21.1.3:
>       Successfully uninstalled pip-21.1.3
> Successfully installed pip-21.3.1
> ERROR: Could not find a version that satisfies the requirement modnet==0.1.11 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6)
> ERROR: No matching distribution found for modnet==0.1.11
> ```

Works fine in VS Code on my local Windows machine, however.
```python
conda create -n modnet python==3.8
conda activate modnet
pip install modnet==0.1.11
```
It's not super important for me to get it running on Google Colab since it's running locally just fine (just tried Google Colab first), but thought I should at least share. Google searches such as:
"pip install not finding latest version" or "pip google colab latest packages not recognized" were unfruitful for me. Might be an issue on Google Colab's side, too.

**Comment by ppdebreuck** [comment]
Interesting. It seems that this is due to the python version of Google Colab (3.7.x), while modnet>0.1.6 requires python 3.8. Changing python version on Collab doesn't seem straightforward. We might be less strict on the python version of modnet... Thanks for pointing out ! 👍

**Comment by Pepe-Marquez** [comment]
Since collab got bumped to 3.8 I guess this issue can be closed?

**Comment by ml-evs** [comment]
> Since collab got bumped to 3.8 I guess this issue can be closed?

Good point, thanks!
