### ISSUE TITLE
Problems featurizing structural dataset with DeBreuck2020Featurizer

### ISSUE THREAD

**Issue by FedeOtto** [ppdebreuck/modnet#81]
Trying to featurize the structures in `matbench_jdft2d` dataset I encounter the following error:

`AttributeError: 'DensityFeatures' object has no attribute 'desired_features'`

That's my code:

```
df = load_dataset('matbench_jdft2d')

featurizer = DeBreuck2020Featurizer()

featurizer.featurize_stucture(df)
```

This error seems to happen for both structural featurisers `DensityFeatures()` and `GlobalSymmetryFeatures()`

**Comment by ml-evs** [comment]
Could you provide the full traceback please, and which matminer version you are using?

**Comment by ppdebreuck** [comment]
It mostly happens with a wrongly configured environment. Please make a new env with python 3.8 and `pip install modnet`. Or follow [How to install](https://github.com/ppdebreuck/modnet#how-to-install)

**Comment by FedeOtto** [comment]
Many thanks. It was indeed to a wrongly configured environment.

**Comment by ml-evs** [comment]
Thanks for letting us know @FedeOtto, feel free to report any other issues you have (with MODNet 🙃)!
